version: "3"
services:
  mariadb:
    platform: linux/x86_64
    container_name: mariadb
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=presta_database
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
    networks:
      - prestashop_network
  prestashop:
    platform: linux/x86_64
    container_name: prestashop
    image: prestashop/prestashop:1.7.8-apache
    restart: unless-stopped
    user: root
    depends_on:
      - mariadb
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    networks:
      - prestashop_network
networks:
  prestashop_network: