version: "3"
services:
  mariadb:
    platform: linux/x86_64
    container_name: db
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=BE_186044
      - MYSQL_ROOT_PASSWORD=student
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
  prestashop:
    platform: linux/x86_64
    container_name: prestashop
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    environment:
      - PS_DEV_MODE=0
      - PS_DEBUG_PROFILING=0
    depends_on:
      - mariadb
      - memcached
    ports:
      - 18604:443
      - 18605:80
    volumes:
      - ./src:/var/www/html
  memcached:
    image: memcached:1.6.10
    container_name: BE_186044_memcached
    restart: unless-stopped
